project_id = "wlawjupusugrhojbywyq"

[functions.send-signup-notification]
verify_jwt = false

[functions.send-smtp-notification]
verify_jwt = false

[functions.send-email-notification]
verify_jwt = false

[functions.send-whatsapp-notification]
verify_jwt = false

[functions.send-notification-api]
verify_jwt = false

[functions.send-custom-webhook]
verify_jwt = false
