# Supabase project configuration - Updated 2025-09-25
project_id = "wlawjupusugrhojbywyq"

[functions.send-signup-notification]
verify_jwt = false

[functions.send-smtp-notification]
verify_jwt = false

[functions.send-email-notification]
verify_jwt = false

[functions.send-whatsapp-notification]
verify_jwt = false
