project_id = "wlawjupusugrhojbywyq"

[functions.send-signup-notification]
verify_jwt = false

[functions.send-smtp-notification]
verify_jwt = false

[functions.send-email-notification]
verify_jwt = false

[functions.send-whatsapp-notification]
verify_jwt = false