
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlawjupusugrhojbywyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsYXdqdXB1c3VncmhvamJ5d3lxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMTIxOTYsImV4cCI6MjA2MTU4ODE5Nn0.-TMflVxBkU4MTTxRWd0jrSiNBCLhxnl8R4EqsrWrSlg";

// Configure auth persistence options with properly typed flowType
const supabaseOptions = {
  auth: {
    storage: localStorage,
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    flowType: 'implicit' as const
  }
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, supabaseOptions);

// Enhanced authentication helper for demo purposes
export const requireAuth = async (callback: () => Promise<any>) => {
  try {
    // First check if we have a real session
    const { data: { session }, error } = await supabase.auth.getSession();
    
    if (error) {
      console.error("Error checking session:", error);
      throw new Error('Authentication verification failed');
    }
    
    // If we have a real session, proceed with the callback
    if (session) {
      console.log("Real authentication confirmed, executing protected operation");
      return callback();
    }
    
    // If no real session, check for demo credentials
    const mockRole = localStorage.getItem('userRole');
    const demoEmails = ['admin@gym.com', 'trainer@gym.com', 'user@gym.com'];
    const isDemoUser = mockRole && demoEmails.some(email => email.includes(mockRole.toLowerCase()));
    
    if (isDemoUser) {
      console.log("Using demo credentials - creating mock session");
      // Create a synthetic demo session to satisfy Supabase's requirements
      // This works because we're using the demo credentials as a special case
      await supabase.auth.signInWithPassword({
        email: `${mockRole}@gym.com`,
        password: `${mockRole}123`
      }).catch(() => {
        // Silently catch this error since we're just trying to establish a session
        console.log("Demo credential authentication attempted");
      });
      
      // Now there should be a session (real or synthetic)
      const { data: { session: newSession } } = await supabase.auth.getSession();
      
      if (newSession) {
        console.log("Session established for demo user, executing operation");
        return callback();
      }
      
      // If we still don't have a session, proceed anyway for demo purposes
      console.log("No session established, but proceeding for demo user");
      return callback();
    }
    
    // If we get here, there's no session and no demo credentials
    console.error("No active session found and not using demo credentials");
    throw new Error('Authentication required');
  } catch (error) {
    console.error("Authentication error:", error);
    throw error;
  }
};
