
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlawjupusugrhojbywyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsYXdqdXB1c3VncmhvamJ5d3lxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMTIxOTYsImV4cCI6MjA2MTU4ODE5Nn0.-TMflVxBkU4MTTxRWd0jrSiNBCLhxnl8R4EqsrWrSlg";

// Configure auth persistence options
const supabaseOptions = {
  auth: {
    storage: localStorage,
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: false
  },
  global: {
    fetch: (...args: [RequestInfo | URL, RequestInit?]) => {
      // Enhanced fetch with improved retry mechanism
      const [resource, config] = args;
      
      // Use AbortController for timeout handling
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 45000); // Extended to 45 seconds
      
      // Add signal to the request config
      const updatedConfig = {
        ...config,
        signal: controller.signal,
        headers: {
          ...config?.headers,
          // Add cache control headers to prevent stale responses
          'Cache-Control': 'no-cache, no-store',
          'Pragma': 'no-cache'
        }
      };
      
      // Implementation of retry logic
      const MAX_RETRIES = 3;
      let retryCount = 0;
      
      const fetchWithRetry = async (): Promise<Response> => {
        try {
          const response = await fetch(resource, updatedConfig);
          clearTimeout(timeoutId);
          return response;
        } catch (error) {
          clearTimeout(timeoutId);
          
          // If we still have retries left and it's a network error, try again
          if (retryCount < MAX_RETRIES && 
              (error instanceof Error && error.name === 'AbortError' || 
               error instanceof TypeError && error.message.includes('Network'))) {
            
            retryCount++;
            console.log(`Retrying database connection (attempt ${retryCount}/${MAX_RETRIES})...`);
            
            // Exponential backoff: 1s, 2s, 4s
            const backoffTime = Math.pow(2, retryCount - 1) * 1000;
            
            return new Promise(resolve => {
              setTimeout(() => resolve(fetchWithRetry()), backoffTime);
            });
          }
          
          // Log detailed error information to help with debugging
          console.error(`Supabase fetch error for ${resource}:`, error);
          
          // Rethrow with more descriptive message
          throw error instanceof Error ? 
            new Error(`Database connection failed: ${error.message}`) : 
            new Error('Database connection failed');
        }
      };
      
      return fetchWithRetry();
    }
  }
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, supabaseOptions);

// Security helper function to check if a user is authenticated before making DB calls
export const requireAuth = async (callback: () => Promise<any>) => {
  const { data: { session } } = await supabase.auth.getSession();
  if (!session) {
    throw new Error('Authentication required');
  }
  return callback();
};
